export { defaultFilename, exportSTL, typeLabel } from './geometry/export'
export { cutoutPoints, plateRect, unitedCutouts } from './geometry/polygons'
export { buildScene } from './geometry/scene'
export type { Vec2 } from './geometry/shapes'
export { localPolygon } from './geometry/shapes'
export { insertDimension } from './types'
